# DO NOT move .notdef from the front of the file!
['.notdef']
codepoints = [0xFFFD]
image = "notdef.png"

['space']
codepoints = [0x20]
image = "0020.png"

['exclam']
codepoints = [0x21]
image = "0021.png"

['quotedbl']
codepoints = [0x22]
image = "0022.png"

['numbersign']
codepoints = [0x23]
image = "0023.png"

['dollar']
codepoints = [0x24]
image = "0024.png"

['percent']
codepoints = [0x25]
image = "0025.png"

['ampersand']
codepoints = [0x26]
image = "0026.png"

['quotesingle']
codepoints = [0x27]
image = "0027.png"

['parenleft']
codepoints = [0x28]
image = "0028.png"

['parenright']
codepoints = [0x29]
image = "0029.png"

['asterisk']
codepoints = [0x2A]
image = "002A.png"

['plus']
codepoints = [0x2B]
image = "002B.png"

['comma']
codepoints = [0x2C]
image = "002C.png"

['hyphen']
codepoints = [0x2D]
image = "002D.png"

['period']
codepoints = [0x2E]
image = "002E.png"

['slash']
codepoints = [0x2F]
image = "002F.png"

['zero']
codepoints = [0x30]
image = "0030.png"

['one']
codepoints = [0x31]
image = "0031.png"

['two']
codepoints = [0x32]
image = "0032.png"

['three']
codepoints = [0x33]
image = "0033.png"

['four']
codepoints = [0x34]
image = "0034.png"

['five']
codepoints = [0x35]
image = "0035.png"

['six']
codepoints = [0x36]
image = "0036.png"

['seven']
codepoints = [0x37]
image = "0037.png"

['eight']
codepoints = [0x38]
image = "0038.png"

['nine']
codepoints = [0x39]
image = "0039.png"

['colon']
codepoints = [0x3A]
image = "003A.png"

['semicolon']
codepoints = [0x3B]
image = "003B.png"

['less']
codepoints = [0x3C]
image = "003C.png"

['equal']
codepoints = [0x3D]
image = "003D.png"

['greater']
codepoints = [0x3E]
image = "003E.png"

['question']
codepoints = [0x3F]
image = "003F.png"

['at']
codepoints = [0x40]
image = "0040.png"

['A']
codepoints = [0x41]
image = "0041.png"

['B']
codepoints = [0x42]
image = "0042.png"

['C']
codepoints = [0x43]
image = "0043.png"

['D']
codepoints = [0x44]
image = "0044.png"

['E']
codepoints = [0x45]
image = "0045.png"

['F']
codepoints = [0x46]
image = "0046.png"

['G']
codepoints = [0x47]
image = "0047.png"

['H']
codepoints = [0x48]
image = "0048.png"

['I']
codepoints = [0x49]
image = "0049.png"

['J']
codepoints = [0x4A]
image = "004A.png"

['K']
codepoints = [0x4B]
image = "004B.png"

['L']
codepoints = [0x4C]
image = "004C.png"

['M']
codepoints = [0x4D]
image = "004D.png"

['N']
codepoints = [0x4E]
image = "004E.png"

['O']
codepoints = [0x4F]
image = "004F.png"

['P']
codepoints = [0x50]
image = "0050.png"

['Q']
codepoints = [0x51]
image = "0051.png"

['R']
codepoints = [0x52]
image = "0052.png"

['S']
codepoints = [0x53]
image = "0053.png"

['T']
codepoints = [0x54]
image = "0054.png"

['U']
codepoints = [0x55]
image = "0055.png"

['V']
codepoints = [0x56]
image = "0056.png"

['W']
codepoints = [0x57]
image = "0057.png"

['X']
codepoints = [0x58]
image = "0058.png"

['Y']
codepoints = [0x59]
image = "0059.png"

['Z']
codepoints = [0x5A]
image = "005A.png"

['bracketleft']
codepoints = [0x5B]
image = "005B.png"

['backslash']
codepoints = [0x5C]
image = "005C.png"

['bracketright']
codepoints = [0x5D]
image = "005D.png"

['asciicircum']
codepoints = [0x5E]
image = "005E.png"

['underscore']
codepoints = [0x5F]
image = "005F.png"

['grave']
codepoints = [0x60]
image = "0060.png"

['a']
codepoints = [0x61]
image = "0061.png"

['b']
codepoints = [0x62]
image = "0062.png"

['c']
codepoints = [0x63]
image = "0063.png"

['d']
codepoints = [0x64]
image = "0064.png"

['e']
codepoints = [0x65]
image = "0065.png"

['f']
codepoints = [0x66]
image = "0066.png"

['g']
codepoints = [0x67]
image = "0067.png"

['h']
codepoints = [0x68]
image = "0068.png"

['i']
codepoints = [0x69]
image = "0069.png"

['j']
codepoints = [0x6A]
image = "006A.png"

['k']
codepoints = [0x6B]
image = "006B.png"

['l']
codepoints = [0x6C]
image = "006C.png"

['m']
codepoints = [0x6D]
image = "006D.png"

['n']
codepoints = [0x6E]
image = "006E.png"

['o']
codepoints = [0x6F]
image = "006F.png"

['p']
codepoints = [0x70]
image = "0070.png"

['q']
codepoints = [0x71]
image = "0071.png"

['r']
codepoints = [0x72]
image = "0072.png"

['s']
codepoints = [0x73]
image = "0073.png"

['t']
codepoints = [0x74]
image = "0074.png"

['u']
codepoints = [0x75]
image = "0075.png"

['v']
codepoints = [0x76]
image = "0076.png"

['w']
codepoints = [0x77]
image = "0077.png"

['x']
codepoints = [0x78]
image = "0078.png"

['y']
codepoints = [0x79]
image = "0079.png"

['z']
codepoints = [0x7A]
image = "007A.png"

['braceleft']
codepoints = [0x7B]
image = "007B.png"

['bar']
codepoints = [0x7C]
image = "007C.png"

['braceright']
codepoints = [0x7D]
image = "007D.png"

['asciitilde']
codepoints = [0x7E]
image = "007E.png"

['uni00A0']
codepoints = [0xA0]
image = "00A0.png"

['exclamdown']
codepoints = [0xA1]
image = "00A1.png"

['cent']
codepoints = [0xA2]
image = "00A2.png"

['sterling']
codepoints = [0xA3]
image = "00A3.png"

['yen']
codepoints = [0xA5]
image = "00A5.png"

['section']
codepoints = [0xA7]
image = "00A7.png"

['dieresis']
codepoints = [0xA8]
image = "00A8.png"

['copyright']
codepoints = [0xA9]
image = "00A9.png"

['ordfeminine']
codepoints = [0xAA]
image = "00AA.png"

['guillemetleft']
codepoints = [0xAB]
image = "00AB.png"

['registered']
codepoints = [0xAE]
image = "00AE.png"

['macron']
codepoints = [0xAF]
image = "00AF.png"

['degree']
codepoints = [0xB0]
image = "00B0.png"

['acute']
codepoints = [0xB4]
image = "00B4.png"

['paragraph']
codepoints = [0xB6]
image = "00B6.png"

['periodcentered']
codepoints = [0xB7]
image = "00B7.png"

['cedilla']
codepoints = [0xB8]
image = "00B8.png"

['ordmasculine']
codepoints = [0xBA]
image = "00BA.png"

['guillemetright']
codepoints = [0xBB]
image = "00BB.png"

['questiondown']
codepoints = [0xBF]
image = "00BF.png"

['Agrave']
codepoints = [0xC0]
image = "00C0.png"

['Aacute']
codepoints = [0xC1]
image = "00C1.png"

['Acircumflex']
codepoints = [0xC2]
image = "00C2.png"

['Atilde']
codepoints = [0xC3]
image = "00C3.png"

['Adieresis']
codepoints = [0xC4]
image = "00C4.png"

['Aring']
codepoints = [0xC5]
image = "00C5.png"

['AE']
codepoints = [0xC6]
image = "00C6.png"

['Ccedilla']
codepoints = [0xC7]
image = "00C7.png"

['Egrave']
codepoints = [0xC8]
image = "00C8.png"

['Eacute']
codepoints = [0xC9]
image = "00C9.png"

['Ecircumflex']
codepoints = [0xCA]
image = "00CA.png"

['Edieresis']
codepoints = [0xCB]
image = "00CB.png"

['Igrave']
codepoints = [0xCC]
image = "00CC.png"

['Iacute']
codepoints = [0xCD]
image = "00CD.png"

['Icircumflex']
codepoints = [0xCE]
image = "00CE.png"

['Idieresis']
codepoints = [0xCF]
image = "00CF.png"

['Eth']
codepoints = [0xD0]
image = "00D0.png"

['Ntilde']
codepoints = [0xD1]
image = "00D1.png"

['Ograve']
codepoints = [0xD2]
image = "00D2.png"

['Oacute']
codepoints = [0xD3]
image = "00D3.png"

['Ocircumflex']
codepoints = [0xD4]
image = "00D4.png"

['Otilde']
codepoints = [0xD5]
image = "00D5.png"

['Odieresis']
codepoints = [0xD6]
image = "00D6.png"

['multiply']
codepoints = [0xD7]
image = "00D7.png"

['Oslash']
codepoints = [0xD8]
image = "00D8.png"

['Ugrave']
codepoints = [0xD9]
image = "00D9.png"

['Uacute']
codepoints = [0xDA]
image = "00DA.png"

['Ucircumflex']
codepoints = [0xDB]
image = "00DB.png"

['Udieresis']
codepoints = [0xDC]
image = "00DC.png"

['Yacute']
codepoints = [0xDD]
image = "00DD.png"

['Thorn']
codepoints = [0xDE]
image = "00DE.png"

['germandbls']
codepoints = [0xDF]
image = "00DF.png"

['agrave']
codepoints = [0xE0]
image = "00E0.png"

['aacute']
codepoints = [0xE1]
image = "00E1.png"

['acircumflex']
codepoints = [0xE2]
image = "00E2.png"

['atilde']
codepoints = [0xE3]
image = "00E3.png"

['adieresis']
codepoints = [0xE4]
image = "00E4.png"

['aring']
codepoints = [0xE5]
image = "00E5.png"

['ae']
codepoints = [0xE6]
image = "00E6.png"

['ccedilla']
codepoints = [0xE7]
image = "00E7.png"

['egrave']
codepoints = [0xE8]
image = "00E8.png"

['eacute']
codepoints = [0xE9]
image = "00E9.png"

['ecircumflex']
codepoints = [0xEA]
image = "00EA.png"

['edieresis']
codepoints = [0xEB]
image = "00EB.png"

['igrave']
codepoints = [0xEC]
image = "00EC.png"

['iacute']
codepoints = [0xED]
image = "00ED.png"

['icircumflex']
codepoints = [0xEE]
image = "00EE.png"

['idieresis']
codepoints = [0xEF]
image = "00EF.png"

['eth']
codepoints = [0xF0]
image = "00F0.png"

['ntilde']
codepoints = [0xF1]
image = "00F1.png"

['ograve']
codepoints = [0xF2]
image = "00F2.png"

['oacute']
codepoints = [0xF3]
image = "00F3.png"

['ocircumflex']
codepoints = [0xF4]
image = "00F4.png"

['otilde']
codepoints = [0xF5]
image = "00F5.png"

['odieresis']
codepoints = [0xF6]
image = "00F6.png"

['divide']
codepoints = [0xF7]
image = "00F7.png"

['oslash']
codepoints = [0xF8]
image = "00F8.png"

['ugrave']
codepoints = [0xF9]
image = "00F9.png"

['uacute']
codepoints = [0xFA]
image = "00FA.png"

['ucircumflex']
codepoints = [0xFB]
image = "00FB.png"

['udieresis']
codepoints = [0xFC]
image = "00FC.png"

['yacute']
codepoints = [0xFD]
image = "00FD.png"

['thorn']
codepoints = [0xFE]
image = "00FE.png"

['ydieresis']
codepoints = [0xFF]
image = "00FF.png"

['Amacron']
codepoints = [0x0100]
image = "0100.png"

['amacron']
codepoints = [0x0101]
image = "0101.png"

['Abreve']
codepoints = [0x0102]
image = "0102.png"

['abreve']
codepoints = [0x0103]
image = "0103.png"

['Aogonek']
codepoints = [0x0104]
image = "0104.png"

['aogonek']
codepoints = [0x0105]
image = "0105.png"

['Cacute']
codepoints = [0x0106]
image = "0106.png"

['cacute']
codepoints = [0x0107]
image = "0107.png"

['Cdotaccent']
codepoints = [0x010A]
image = "010A.png"

['cdotaccent']
codepoints = [0x010B]
image = "010B.png"

['Ccaron']
codepoints = [0x010C]
image = "010C.png"

['ccaron']
codepoints = [0x010D]
image = "010D.png"

['Dcaron']
codepoints = [0x010E]
image = "010E.png"

['dcaron']
codepoints = [0x010F]
image = "010F.png"

['Dcroat']
codepoints = [0x0110]
image = "0110.png"

['dcroat']
codepoints = [0x0111]
image = "0111.png"

['Emacron']
codepoints = [0x0112]
image = "0112.png"

['emacron']
codepoints = [0x0113]
image = "0113.png"

['Edotaccent']
codepoints = [0x0116]
image = "0116.png"

['edotaccent']
codepoints = [0x0117]
image = "0117.png"

['Eogonek']
codepoints = [0x0118]
image = "0118.png"

['eogonek']
codepoints = [0x0119]
image = "0119.png"

['Ecaron']
codepoints = [0x011A]
image = "011A.png"

['ecaron']
codepoints = [0x011B]
image = "011B.png"

['Gbreve']
codepoints = [0x011E]
image = "011E.png"

['gbreve']
codepoints = [0x011F]
image = "011F.png"

['Gdotaccent']
codepoints = [0x0120]
image = "0120.png"

['gdotaccent']
codepoints = [0x0121]
image = "0121.png"

['Gcommaaccent']
codepoints = [0x0122]
image = "0122.png"

['gcommaaccent']
codepoints = [0x0123]
image = "0123.png"

['Hbar']
codepoints = [0x0126]
image = "0126.png"

['hbar']
codepoints = [0x0127]
image = "0127.png"

['Imacron']
codepoints = [0x012A]
image = "012A.png"

['imacron']
codepoints = [0x012B]
image = "012B.png"

['Iogonek']
codepoints = [0x012E]
image = "012E.png"

['iogonek']
codepoints = [0x012F]
image = "012F.png"

['Idotaccent']
codepoints = [0x0130]
image = "0130.png"

['idotless']
codepoints = [0x0131]
image = "0131.png"

['Kcommaaccent']
codepoints = [0x0136]
image = "0136.png"

['kcommaaccent']
codepoints = [0x0137]
image = "0137.png"

['Lacute']
codepoints = [0x0139]
image = "0139.png"

['lacute']
codepoints = [0x013A]
image = "013A.png"

['Lcommaaccent']
codepoints = [0x013B]
image = "013B.png"

['lcommaaccent']
codepoints = [0x013C]
image = "013C.png"

['Lcaron']
codepoints = [0x013D]
image = "013D.png"

['lcaron']
codepoints = [0x013E]
image = "013E.png"

['Lslash']
codepoints = [0x0141]
image = "0141.png"

['lslash']
codepoints = [0x0142]
image = "0142.png"

['Nacute']
codepoints = [0x0143]
image = "0143.png"

['nacute']
codepoints = [0x0144]
image = "0144.png"

['Ncommaaccent']
codepoints = [0x0145]
image = "0145.png"

['ncommaaccent']
codepoints = [0x0146]
image = "0146.png"

['Ncaron']
codepoints = [0x0147]
image = "0147.png"

['ncaron']
codepoints = [0x0148]
image = "0148.png"

['Ohungarumlaut']
codepoints = [0x0150]
image = "0150.png"

['ohungarumlaut']
codepoints = [0x0151]
image = "0151.png"

['OE']
codepoints = [0x0152]
image = "0152.png"

['oe']
codepoints = [0x0153]
image = "0153.png"

['Racute']
codepoints = [0x0154]
image = "0154.png"

['racute']
codepoints = [0x0155]
image = "0155.png"

['Rcaron']
codepoints = [0x0158]
image = "0158.png"

['rcaron']
codepoints = [0x0159]
image = "0159.png"

['Sacute']
codepoints = [0x015A]
image = "015A.png"

['sacute']
codepoints = [0x015B]
image = "015B.png"

['Scedilla']
codepoints = [0x015E]
image = "015E.png"

['scedilla']
codepoints = [0x015F]
image = "015F.png"

['Scaron']
codepoints = [0x0160]
image = "0160.png"

['scaron']
codepoints = [0x0161]
image = "0161.png"

['Tcaron']
codepoints = [0x0164]
image = "0164.png"

['tcaron']
codepoints = [0x0165]
image = "0165.png"

['Umacron']
codepoints = [0x016A]
image = "016A.png"

['umacron']
codepoints = [0x016B]
image = "016B.png"

['Uring']
codepoints = [0x016E]
image = "016E.png"

['uring']
codepoints = [0x016F]
image = "016F.png"

['Uhungarumlaut']
codepoints = [0x0170]
image = "0170.png"

['uhungarumlaut']
codepoints = [0x0171]
image = "0171.png"

['Uogonek']
codepoints = [0x0172]
image = "0172.png"

['uogonek']
codepoints = [0x0173]
image = "0173.png"

['Wcircumflex']
codepoints = [0x0174]
image = "0174.png"

['wcircumflex']
codepoints = [0x0175]
image = "0175.png"

['Ycircumflex']
codepoints = [0x0176]
image = "0176.png"

['ycircumflex']
codepoints = [0x0177]
image = "0177.png"

['Ydieresis']
codepoints = [0x0178]
image = "0178.png"

['Zacute']
codepoints = [0x0179]
image = "0179.png"

['zacute']
codepoints = [0x017A]
image = "017A.png"

['Zdotaccent']
codepoints = [0x017B]
image = "017B.png"

['zdotaccent']
codepoints = [0x017C]
image = "017C.png"

['Zcaron']
codepoints = [0x017D]
image = "017D.png"

['zcaron']
codepoints = [0x017E]
image = "017E.png"

['Scommaaccent']
codepoints = [0x0218]
image = "0218.png"

['scommaaccent']
codepoints = [0x0219]
image = "0219.png"

['Tcommaaccent']
codepoints = [0x021A]
image = "021A.png"

['tcommaaccent']
codepoints = [0x021B]
image = "021B.png"

['jdotless']
codepoints = [0x0237]
image = "0237.png"

['circumflex']
codepoints = [0x02C6]
image = "02C6.png"

['caron']
codepoints = [0x02C7]
image = "02C7.png"

['breve']
codepoints = [0x02D8]
image = "02D8.png"

['dotaccent']
codepoints = [0x02D9]
image = "02D9.png"

['ring']
codepoints = [0x02DA]
image = "02DA.png"

['ogonek']
codepoints = [0x02DB]
image = "02DB.png"

['tilde']
codepoints = [0x02DC]
image = "02DC.png"

['hungarumlaut']
codepoints = [0x02DD]
image = "02DD.png"

['gravecomb']
codepoints = [0x0300]
image = "0300.png"

['acutecomb']
codepoints = [0x0301]
image = "0301.png"

['circumflexcomb']
codepoints = [0x0302]
image = "0302.png"

['tildecomb']
codepoints = [0x0303]
image = "0303.png"

['macroncomb']
codepoints = [0x0304]
image = "0304.png"

['brevecomb']
codepoints = [0x0306]
image = "0306.png"

['dotaccentcomb']
codepoints = [0x0307]
image = "0307.png"

['dieresiscomb']
codepoints = [0x0308]
image = "0308.png"

['ringcomb']
codepoints = [0x030A]
image = "030A.png"

['hungarumlautcomb']
codepoints = [0x030B]
image = "030B.png"

['caroncomb']
codepoints = [0x030C]
image = "030C.png"

['commaaccentcomb']
codepoints = [0x0326]
image = "0326.png"

['cedillacomb']
codepoints = [0x0327]
image = "0327.png"

['ogonekcomb']
codepoints = [0x0328]
image = "0328.png"

['Wgrave']
codepoints = [0x1E80]
image = "1E80.png"

['wgrave']
codepoints = [0x1E81]
image = "1E81.png"

['Wacute']
codepoints = [0x1E82]
image = "1E82.png"

['wacute']
codepoints = [0x1E83]
image = "1E83.png"

['Wdieresis']
codepoints = [0x1E84]
image = "1E84.png"

['wdieresis']
codepoints = [0x1E85]
image = "1E85.png"

['Germandbls']
codepoints = [0x1E9E]
image = "1E9E.png"

['Ygrave']
codepoints = [0x1EF2]
image = "1EF2.png"

['ygrave']
codepoints = [0x1EF3]
image = "1EF3.png"

['endash']
codepoints = [0x2013]
image = "2013.png"

['emdash']
codepoints = [0x2014]
image = "2014.png"

['quoteleft']
codepoints = [0x2018]
image = "2018.png"

['quoteright']
codepoints = [0x2019]
image = "2019.png"

['quotesinglbase']
codepoints = [0x201A]
image = "201A.png"

['quotedblleft']
codepoints = [0x201C]
image = "201C.png"

['quotedblright']
codepoints = [0x201D]
image = "201D.png"

['quotedblbase']
codepoints = [0x201E]
image = "201E.png"

['bullet']
codepoints = [0x2022]
image = "2022.png"

['ellipsis']
codepoints = [0x2026]
image = "2026.png"

['guilsinglleft']
codepoints = [0x2039]
image = "2039.png"

['guilsinglright']
codepoints = [0x203A]
image = "203A.png"

['euro']
codepoints = [0x20AC]
image = "20AC.png"

['trademark']
codepoints = [0x2122]
image = "2122.png"

['minus']
codepoints = [0x2212]
image = "2212.png"

['_0']
codepoints = [0x2260]
image = "2260.png"

['_1']
codepoints = [0x2265]
image = "2265.png"

['_2']
codepoints = [0x2264]
image = "2264.png"

['_3']
codepoints = [0xB1]
image = "00B1.png"

['_4']
codepoints = [0x2248]
image = "2248.png"

['_5']
codepoints = [0xAC]
image = "00AC.png"

['_6']
codepoints = [0x221E]
image = "221E.png"

['_7']
codepoints = [0xB2]
image = "00B2.png"

['_8']
codepoints = [0xB3]
image = "00B3.png"

['_9']
codepoints = [0x2032]
image = "2032.png"

['_A']
codepoints = [0x2033]
image = "2033.png"

['_B']
codepoints = [0x013F]
image = "013F.png"

['_C']
codepoints = [0x0140]
image = "0140.png"

['_D']
codepoints = [0x014A]
image = "014A.png"

['_E']
codepoints = [0x014B]
image = "014B.png"

['_F']
codepoints = [0x0166]
image = "0166.png"

['_G']
codepoints = [0x0167]
image = "0167.png"

['_H']
codepoints = [0x01B7]
image = "01B7.png"

['_I']
codepoints = [0x01E4]
image = "01E4.png"

['_J']
codepoints = [0x01E5]
image = "01E5.png"

['_K']
codepoints = [0x01EE]
image = "01EE.png"

['_L']
codepoints = [0x01EF]
image = "01EF.png"

['_M']
codepoints = [0x0292]
image = "0292.png"

['_N']
codepoints = [0x017F]
image = "017F.png"

['_O']
codepoints = [0x0132]
image = "0132.png"

['_P']
codepoints = [0x0133]
image = "0133.png"

['_Q']
codepoints = [0x016C]
image = "016C.png"

['_R']
codepoints = [0x016D]
image = "016D.png"

